package com.mycompany.practica1compiladores.view;

import java.io.File;

/**
 * @author giovanic
 */
public class Tab extends javax.swing.JPanel {

    private File archivo;

    /**
     * Creates new form Tab
     *
     * @param archivo archivo que contentra el panel
     */
    public Tab(File archivo) {
        initComponents();
        this.archivo = archivo;

        NumeroLinea numeroLinea = new NumeroLinea(vistaContenido);
        jScrollPane1.setRowHeaderView(numeroLinea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        popupCopiar = new javax.swing.JMenuItem();
        popupPegar = new javax.swing.JMenuItem();
        popupCortar = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        vistaContenido = new javax.swing.JTextArea();

        popupCopiar.setText("Copiar");
        popupCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupCopiarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popupCopiar);

        popupPegar.setText("Pegar");
        popupPegar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupPegarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popupPegar);

        popupCortar.setText("Cortar");
        popupCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupCortarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popupCortar);

        vistaContenido.setColumns(20);
        vistaContenido.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        vistaContenido.setRows(5);
        vistaContenido.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(vistaContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void popupCopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupCopiarActionPerformed
        vistaContenido.copy();
    }//GEN-LAST:event_popupCopiarActionPerformed

    private void popupPegarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupPegarActionPerformed
        vistaContenido.paste();
    }//GEN-LAST:event_popupPegarActionPerformed

    private void popupCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupCortarActionPerformed
        vistaContenido.cut();
    }//GEN-LAST:event_popupCortarActionPerformed

    public void editarVista(String contenido) {
        vistaContenido.setText(contenido);
    }

    public File getArchivo() {
        return archivo;
    }

    public void setArchivo(File archivo) {
        this.archivo = archivo;
    }

    public String getVistaContenido() {
        return vistaContenido.getText().trim().replaceAll("[\r\n]+$", "");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem popupCopiar;
    private javax.swing.JMenuItem popupCortar;
    private javax.swing.JMenuItem popupPegar;
    private javax.swing.JTextArea vistaContenido;
    // End of variables declaration//GEN-END:variables
}
