package com.mycompany.practica1compiladores.view;

import com.mycompany.practica1compiladores.backend.utilities.FilesControl;
import com.mycompany.practica1compiladores.backend.utilities.GestionTab;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.util.Objects;

/**
 * @author giovanic
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private final FilesControl control;
    private final GestionTab gestionTab;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();

        setLocationRelativeTo(null);
        this.control = new FilesControl();
        this.gestionTab = new GestionTab(tab, control);
        Image icon = new ImageIcon(getClass().getResource("/logoTransparente.png")).getImage();
        setIconImage(icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        nuevoMenuItem = new javax.swing.JMenuItem();
        abrirMenuItem = new javax.swing.JMenuItem();
        guardarMenuItem = new javax.swing.JMenuItem();
        eliminarTabMenuItem = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        verReporteItemMenu = new javax.swing.JMenuItem();
        SimbolTab = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FIGURAS");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        menuArchivo.setText("Accion");

        nuevoMenuItem.setText("Nuevo Archivo");
        nuevoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(nuevoMenuItem);

        abrirMenuItem.setText("Abrir Archivo");
        abrirMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(abrirMenuItem);

        guardarMenuItem.setText("Guardar Archivo");
        guardarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(guardarMenuItem);

        eliminarTabMenuItem.setText("Eliminar Pestaña");
        eliminarTabMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTabMenuItemActionPerformed(evt);
            }
        });
        menuArchivo.add(eliminarTabMenuItem);

        barraMenu.add(menuArchivo);

        menuReport.setText("Reportes");

        verReporteItemMenu.setText("Ver Reportes");
        verReporteItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verReporteItemMenuActionPerformed(evt);
            }
        });
        menuReport.add(verReporteItemMenu);

        SimbolTab.setText("Tabla de Simbolos");
        SimbolTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimbolTabActionPerformed(evt);
            }
        });
        menuReport.add(SimbolTab);

        barraMenu.add(menuReport);

        jMenu1.setText("build");

        jMenuItem1.setText("Run");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        barraMenu.add(jMenu1);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoMenuItemActionPerformed
        File archivo = control.crearArchivo();
        if (!Objects.isNull(archivo)) {
            String contenido = control.getContenido(archivo.getAbsolutePath());
            gestionTab.addTab(archivo, contenido);
        }
    }//GEN-LAST:event_nuevoMenuItemActionPerformed

    private void abrirMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirMenuItemActionPerformed
        File archivo = control.getFile();
        if (!Objects.isNull(archivo)) {
            String contenido = control.getContenido(archivo.getAbsolutePath());
            gestionTab.addTab(archivo, contenido);
        }
    }//GEN-LAST:event_abrirMenuItemActionPerformed

    private void guardarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarMenuItemActionPerformed
        if (tab.getSelectedIndex() != -1) {
            gestionTab.sobreEscribir(tab.getSelectedIndex());
        }
    }//GEN-LAST:event_guardarMenuItemActionPerformed

    private void eliminarTabMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTabMenuItemActionPerformed
        if (tab.getSelectedIndex() != -1) {
            gestionTab.deleteTab(tab.getSelectedIndex());
        } else {
            JOptionPane.showMessageDialog(null, "No hay pesañas que cerrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_eliminarTabMenuItemActionPerformed

    private void verReporteItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verReporteItemMenuActionPerformed

    }//GEN-LAST:event_verReporteItemMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void SimbolTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimbolTabActionPerformed

    }//GEN-LAST:event_SimbolTabActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SimbolTab;
    private javax.swing.JMenuItem abrirMenuItem;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem eliminarTabMenuItem;
    private javax.swing.JMenuItem guardarMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem nuevoMenuItem;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JMenuItem verReporteItemMenu;
    // End of variables declaration//GEN-END:variables
}
