
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.practica1compiladores.backend.analisis;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int LINEA = 11;
  public static final int COL_NARANJA = 20;
  public static final int MENOS = 8;
  public static final int COL_GRIS = 18;
  public static final int RPAREN = 6;
  public static final int DECIMAL = 3;
  public static final int COL_CELESTE = 21;
  public static final int COL_VERDE = 17;
  public static final int CURVA = 12;
  public static final int ANIMAR = 28;
  public static final int CUADRADO = 25;
  public static final int OBJETO = 29;
  public static final int UMENOS = 13;
  public static final int LPAREN = 5;
  public static final int COL_AMARILLO = 16;
  public static final int ID = 4;
  public static final int POR = 9;
  public static final int GRAFICAR = 23;
  public static final int COMA = 31;
  public static final int COL_ROJO = 15;
  public static final int EOF = 0;
  public static final int DIV = 10;
  public static final int POLIGONO = 27;
  public static final int error = 1;
  public static final int COL_VIOLETA = 22;
  public static final int CIRCULO = 24;
  public static final int COL_NEGRO = 19;
  public static final int ENTERO = 2;
  public static final int ANTERIOR = 30;
  public static final int COL_AZUL = 14;
  public static final int RECTANGULO = 26;
  public static final int MAS = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENTERO",
  "DECIMAL",
  "ID",
  "LPAREN",
  "RPAREN",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "LINEA",
  "CURVA",
  "UMENOS",
  "COL_AZUL",
  "COL_ROJO",
  "COL_AMARILLO",
  "COL_VERDE",
  "COL_GRIS",
  "COL_NEGRO",
  "COL_NARANJA",
  "COL_CELESTE",
  "COL_VIOLETA",
  "GRAFICAR",
  "CIRCULO",
  "CUADRADO",
  "RECTANGULO",
  "POLIGONO",
  "ANIMAR",
  "OBJETO",
  "ANTERIOR",
  "COMA"
  };
}

